run:
  deadline: 10m
  go: 1.23

output:
  formats:
    - format: colored-line-number

linters:
  enable:
    - depguard
    - godot
    - gofumpt
    - goimports
    - revive
    - whitespace

issues:
  exclude-dirs:
    - proto/
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck

linters-settings:
  depguard:
    rules:
      Main:
        deny:
          - pkg: sync/atomic
            desc: "Use go.uber.org/atomic instead of sync/atomic"
          - pkg: debug/elf
            desc: "Use github.com/parca-dev/parca/internal/go/debug/elf instead of debug/elf"
          - pkg: github.com/stretchr/testify/assert
            desc: "Use github.com/stretchr/testify/require instead of github.com/stretchr/testify/assert"
          - pkg: log
            desc: "Use github.com/go-kit/log instead of github.com/go-kit/kit/log"
          - pkg: github.com/go-kit/kit/log
            desc: "Use github.com/go-kit/log instead of github.com/go-kit/kit/log"
          - pkg: github.com/go-logr/logr
            desc: "Use github.com/go-kit/log instead of github.com/go-kit/kit/log"
          - pkg: github.com/pkg/errors
            desc: "Use fmt.Errorf instead"
  errcheck:
    exclude-functions:
      - "(github.com/go-kit/log.Logger).Log"
  goimports:
    local-prefixes: github.com/pyrra-dev/pyrra
  gofumpt:
    extra-rules: true
  misspell:
    locale: US
